globalThis.SDGBassSynth=(()=>{
  const FONT_URL='https://static.songsterr.com/midi-player-v0/SGM_Plus_HQ/000-033-Fingered_Bass.sf3',CHANNELS=16,BEND_RANGE=12;
  let context,synth,node,readyPromise,state='idle',error='',voiceSeq=0;const voices=new Map;
  function decode(value){const raw=atob(value),bytes=new Uint8Array(raw.length);for(let i=0;i<raw.length;i++)bytes[i]=raw.charCodeAt(i);return bytes.buffer}
  async function ensure(){if(state==='ready')return true;if(readyPromise)return readyPromise;state='loading';readyPromise=(async()=>{await globalThis.JSSynth.waitForReady();globalThis.JSSynth.disableLogging?.();context=context||new AudioContext({latencyHint:'interactive'});await context.resume();const response=await chrome.runtime.sendMessage({type:'sdg-songsterr-soundfont',url:FONT_URL});if(!response?.ok)throw Error(response?.error||'Bass SoundFont 下載失敗');synth=new globalThis.JSSynth.Synthesizer();synth.init(context.sampleRate,{polyphony:128,reverbActive:true,chorusActive:false,midiChannelCount:CHANNELS});synth.setGain(1.2);const id=await synth.loadSFont(decode(response.base64));for(let channel=0;channel<CHANNELS;channel++){synth.midiProgramSelect(channel,id,0,33);synth.midiPitchWheelSensitivity(channel,BEND_RANGE);synth.midiPitchBend(channel,8192)}node=synth.createAudioNode(context,512);node.connect(context.destination);state='ready';error='';return true})().catch(e=>{state='error';error=e?.message||String(e);readyPromise=null;throw e});return readyPromise}
  function finishVoice(id){let voice=voices.get(id);if(!voice)return;clearTimeout(voice.offTimer);clearInterval(voice.bendTimer);voices.delete(id);try{synth.midiNoteOff(voice.channel,voice.midi);synth.midiPitchBend(voice.channel,8192)}catch{}}
  function acquireChannel(){let used=new Set([...voices.values()].map(v=>v.channel));for(let channel=0;channel<CHANNELS;channel++)if(!used.has(channel))return channel;let oldest=[...voices.values()].sort((a,b)=>a.startedAt-b.startedAt)[0];finishVoice(oldest.id);return oldest.channel}
  function bendValue(semitones){return Math.max(0,Math.min(16383,Math.round(8192+semitones/BEND_RANGE*8192)))}
  function playPerformance(note,quality='PERFECT',volume=1){if(state!=='ready'){ensure().catch(()=>{});return false}context.resume();let full=quality==='PERFECT'||quality==='GREAT'||quality==='AUTO',factor=full?1:(quality==='GOOD'?0.65:0.42),performanceData=note.performance||{},duration=Math.max(60,(performanceData.duration_ms||note.duration_ms||500)*factor),bends=full?(performanceData.bends||[]):[],channel=acquireChannel(),id=++voiceSeq,midi=note.midi??40,velocity=Math.max(1,Math.min(127,Math.round((note.velocity??96)*volume))),voice={id,channel,midi,startedAt:performance.now(),offTimer:0,bendTimer:0};voices.set(id,voice);synth.midiPitchBend(channel,8192);synth.midiNoteOn(channel,midi,velocity);if(bends.length){voice.bendTimer=setInterval(()=>{if(!voices.has(id))return;let elapsed=performance.now()-voice.startedAt,current=0;for(let bend of bends){if(elapsed<bend.startMs)break;if(elapsed>=bend.endMs)current=bend.semitones;else{let p=(elapsed-bend.startMs)/Math.max(1,bend.endMs-bend.startMs);current=bend.fromSemitones+(bend.semitones-bend.fromSemitones)*p;break}}try{synth.midiPitchBend(channel,bendValue(current))}catch{}},8)}voice.offTimer=setTimeout(()=>finishVoice(id),duration);return id}
  function play(midi,velocity=96,durationMs=500,volume=1){return playPerformance({midi,velocity,duration_ms:durationMs},'PERFECT',volume)}
  function stop(midi){let found=false;for(let voice of [...voices.values()])if(voice.midi===midi){finishVoice(voice.id);found=true}return found}
  function stopAll(){for(let voice of [...voices.values()])finishVoice(voice.id);if(state!=='ready')return false;try{synth.midiAllNotesOff(-1);return true}catch{return false}}
  return{ensure,play,playPerformance,stop,stopAll,getState:()=>({state,error,url:FONT_URL,voices:voices.size})};
})();
