(()=>{
if(new URLSearchParams(location.search).get('sdg_mode')!=='bass'||document.querySelector('#sdg-bass-root'))return;
const match=location.href.match(/-s(\d+)(?:t(\d+))?(?:\/r(\d+))?/);if(!match)return;
const songId=+match[1],urlRevision=match[3]?+match[3]:null,colors=['#ef405b','#45d67d','#3a9cff','#ffd23f','#d765ff'],codes=['KeyA','KeyS','KeyD','KeyF','KeyG'],names=['A','S','D','F','G'];
let chart=[],iframe,current=0,duration=0,started=false,held=new Set(),judged=new Set(),nodes=new Map(),combo=0,score=0,offset=0,partId=-1,revisionId=urlRevision,volume=70,activeSustains=[];
const root=document.createElement('div');root.id='sdg-bass-root';root.innerHTML=`<header><button id="sdb-start">開始</button><button id="sdb-pause">暫停 P</button><label>微調 <input id="sdb-offset" type="number" value="0" step=".001"> 秒</label><label>Bass 音量 <input id="sdb-volume" type="range" min="0" max="100" value="70"></label><b id="sdb-track">BASS 譜面載入中…</b><span id="sdb-score">SCORE 0000000　COMBO 0</span><button id="sdb-back">回到播放清單</button></header><main><section id="sdb-playlist"><h2>播放清單</h2><div id="sdb-songs"></div></section><div id="sdb-game"><div class="shade"></div><div class="judge"></div></div><aside><nav id="sdb-instruments"></nav><h2>BASS</h2><p>按住五色品鍵<br>再按 J／K 撥弦</p><div class="keys">${names.map((x,i)=>`<i style="--c:${colors[i]}">${x}</i>`).join('')}</div><strong>J ↑ PICK<br>K ↓ PICK</strong><h3>鍵位與順序</h3><div class="bind-list">${names.map((x,i)=>`<label><i style="--c:${colors[i]}"></i><span>${["RED","GREEN","BLUE","YELLOW","PINK"][i]}</span><b>${x}</b></label>`).join("")}<label><i class="pick"></i><span>PICK ↑</span><b>J</b></label><label><i class="pick"></i><span>PICK ↓</span><b>K</b></label></div></aside></main>`;document.documentElement.append(root);
const $=s=>root.querySelector(s),game=$('#sdb-game');async function renderBassPlaylist(){let {playlist=[]}=await chrome.storage.local.get('playlist');$('#sdb-songs').innerHTML=[...playlist].reverse().map(x=>`<button data-url="${x.url}"><b>${x.title}</b><small>${x.artist||''}</small></button>`).join('');$('#sdb-songs').querySelectorAll('button').forEach(button=>button.onclick=()=>location.href=button.dataset.url)}async function saveBassSettings(){await chrome.storage.local.set({bassSettings:{volume,offset}})}
function command(func,args=[]){iframe?.contentWindow?.postMessage(JSON.stringify({event:'command',func,args,id:iframe.id}),'*')}
function player(){iframe=document.querySelector('iframe[id^="youtube-player-"]');if(iframe&&!game.contains(iframe)){iframe.classList.add('sdb-video');game.prepend(iframe)}return iframe}
function instrumentUrl(part,mode){let url=new URL(`https://www.songsterr.com/a/wsa/song-tab-s${songId}t${part}/r${revisionId}`);if(mode!=='drums')url.searchParams.set('sdg_mode',mode);return url.href}function renderInstrumentSelector(meta){let tracks=meta.tracks||[],drum=tracks.findIndex(t=>t.instrumentId===1024&&!t.isEmpty),bass=tracks.findIndex(t=>/bass/i.test(t.instrument||'')&&!t.isEmpty),guitars=tracks.map((t,i)=>({...t,index:i})).filter(t=>/guitar/i.test(t.instrument||'')&&!t.isEmpty),nav=$('#sdb-instruments');nav.innerHTML=`<b>樂器選擇</b><div>${drum>=0?`<button data-part="${drum}" data-mode="drums">鼓</button>`:''}${bass>=0?`<button class="active" data-part="${bass}" data-mode="bass">BASS</button>`:''}${guitars[0]?'<button disabled>吉他（主KEY）</button>':''}${guitars[1]?'<button disabled>吉他（節奏）</button>':''}</div>`;nav.querySelectorAll('button[data-part]').forEach(button=>button.onclick=()=>{command('pauseVideo');location.href=instrumentUrl(button.dataset.part,button.dataset.mode)})}function velocityValue(v,fallback=96){if(Number.isFinite(Number(v)))return Math.max(1,Math.min(127,+v));return({ppp:16,pp:32,p:48,mp:64,mf:80,f:96,ff:112,fff:127}[String(v||'').toLowerCase()]??fallback)}
function parse(source,points){let raw=[],spans=points.slice(1).map((x,i)=>x-points[i]),typical=[...spans].sort((a,b)=>a-b)[Math.floor(spans.length/2)]||1.83,tempo=(source.automations?.tempo||[]).slice().sort((a,b)=>a.measure-b.measure||a.position-b.position),bpm=tempo[0]?.bpm||120,tuning=source.tuning||[];source.measures.forEach((m,mi)=>{let change=tempo.filter(x=>x.measure<=mi).at(-1);if(change?.bpm)bpm=change.bpm;for(const voice of m.voices||[]){let p=0,velocity=96;for(const beat of voice.beats||[]){velocity=velocityValue(beat.velocity,velocity);let d=beat.duration||[0,1],beatUnits=d[1]?4*d[0]/d[1]:0,measureUnits=Math.max(4,(voice.beats||[]).reduce((sum,b)=>{let x=b.duration||[0,1];return sum+(x[1]?4*x[0]/x[1]:0)},0)),start=+points[mi],end=mi+1<points.length?+points[mi+1]:start+typical,time=(start+p/measureUnits*(end-start))*1000,durationMs=beatUnits/measureUnits*(end-start)*1000,notes=(beat.notes||[]).filter(n=>!n.rest&&Number.isFinite(n.fret)&&Number.isFinite(n.string)).map(n=>({midi:(tuning[n.string]??28)+n.fret,fret:n.fret,string:n.string}));if(notes.length)raw.push({time_ms:time,duration_ms:durationMs,velocity,notes});p+=beatUnits}}});let pitches=raw.flatMap(x=>x.notes.map(n=>n.midi)),min=Math.min(...pitches),max=Math.max(...pitches);for(const event of raw){let used=new Set();for(const note of event.notes){let lane=max===min?2:Math.round((note.midi-min)/(max-min)*4);while(used.has(lane)&&lane<4)lane++;while(used.has(lane)&&lane>0)lane--;used.add(lane);note.lane=lane}event.lanes=[...used].sort()}return raw.sort((a,b)=>a.time_ms-b.time_ms)}
async function load(){try{await renderBassPlaylist();let {bassSettings={}}=await chrome.storage.local.get('bassSettings');volume=Number.isFinite(bassSettings.volume)?bassSettings.volume:70;offset=Number.isFinite(bassSettings.offset)?bassSettings.offset:0;$('#sdb-volume').value=volume;$('#sdb-offset').value=(offset/1000).toFixed(3);let meta=await fetch(`https://www.songsterr.com/api/meta/${songId}${urlRevision?'/'+urlRevision:''}`).then(r=>r.json());revisionId=meta.revisionId||meta.latestRevisionId;renderInstrumentSelector(meta);partId=(meta.tracks||[]).findIndex(t=>/bass/i.test(t.instrument||'')&&!t.isEmpty);if(partId<0)throw Error('這首歌沒有 Bass 軌');let source=await fetch(`https://dqsljvtekg760.cloudfront.net/${songId}/${revisionId}/${meta.image}/${partId}.json`).then(r=>r.json()),syncs=await fetch(`https://www.songsterr.com/api/video-points/${songId}/${revisionId}/list`).then(r=>r.json()),videoId=meta.videos?.find(v=>v.status==='done')?.videoId,sync=syncs.find(x=>x.videoId===videoId&&x.status==='done');if(!sync)throw Error('沒有影片同步點');chart=parse(source,sync.points);duration=+sync.points.at(-1)+2;$('#sdb-track').textContent=`${meta.title} · ${meta.tracks[partId].instrument} · ${chart.length} 拍`;await globalThis.SDGBassSynth.ensure();setup();waitPlayer()}catch(e){$('#sdb-track').textContent='Bass 載入失敗：'+e.message}}
function waitPlayer(){if(player()){command('setVolume',[0]);command('pauseVideo');return}$('#sdb-track').textContent+=' · 請先在 Songsterr 點一次原聲播放';setTimeout(waitPlayer,500)}
function setup(){game.querySelectorAll('.lane,.label').forEach(x=>x.remove());for(let i=0;i<5;i++){let lane=document.createElement('div');lane.className='lane';lane.style.cssText=`left:${i*20}%;width:20%;--c:${colors[i]}`;game.append(lane);let label=document.createElement('div');label.className='label';label.style.cssText=`left:${i*20}%;width:20%;color:${colors[i]}`;label.innerHTML=`<span>${['RED','GREEN','BLUE','YELLOW','PINK'][i]}</span><b>${names[i]}</b>`;game.append(label)}}
function gameMs(){return current*1000-offset}
function updateHud(){$('#sdb-score').textContent=`SCORE ${String(score).padStart(7,'0')}　COMBO ${combo}`}
function hit(index){let event=chart[index];judged.add(index);nodes.get(index)?.remove();nodes.delete(index);for(const note of event.notes)globalThis.SDGBassSynth.play(note.midi,event.velocity,event.duration_ms,volume/100);if(event.duration_ms>250)for(const lane of event.lanes)activeSustains.push({lane,until:event.time_ms+event.duration_ms});combo++;score+=1000*combo;updateHud()}
function miss(){combo=0;updateHud()}
function pick(){if(!started)return;let t=gameMs(),best=-1,d=999;chart.forEach((event,i)=>{let x=Math.abs(event.time_ms-t);if(!judged.has(i)&&x<d){best=i;d=x}});if(best<0||d>120)return miss();let need=chart[best].lanes,have=[...held].sort();if(need.length!==have.length||need.some((x,i)=>x!==have[i]))return miss();hit(best)}
function loop(){if(!started)return;let t=gameMs(),lead=2000,height=game.clientHeight-82;activeSustains=activeSustains.filter(x=>x.until>t);chart.forEach((event,i)=>{if(judged.has(i)||event.time_ms<t-160||event.time_ms>t+lead)return;let node=nodes.get(i);if(!node){node=document.createElement('div');node.className='bass-note';for(const lane of event.lanes){let part=document.createElement('i');part.style.cssText=`left:${lane*20+1}%;width:18%;background:${colors[lane]};height:${Math.max(14,event.duration_ms/lead*height)}px`;node.append(part)}game.append(node);nodes.set(i,node)}node.style.top=height-(event.time_ms-t)/lead*(height-15)+'px'});chart.forEach((event,i)=>{if(!judged.has(i)&&event.time_ms<t-150){judged.add(i);nodes.get(i)?.remove();nodes.delete(i);miss()}});requestAnimationFrame(loop)}
addEventListener('message',e=>{let data=e.data;try{if(typeof data==='string')data=JSON.parse(data)}catch{}if(data?.event==='infoDelivery'&&data.info){if(Number.isFinite(data.info.currentTime))current=data.info.currentTime;if(Number.isFinite(data.info.duration))duration=data.info.duration}});
addEventListener('keydown',e=>{let lane=codes.indexOf(e.code);if(lane>=0){e.preventDefault();held.add(lane);game.querySelectorAll('.lane')[lane]?.classList.add('held')}if((e.code==='KeyJ'||e.code==='KeyK')&&!e.repeat){e.preventDefault();pick()}if(e.code==='KeyP'&&!e.repeat)$('#sdb-pause').click()},true);addEventListener('keyup',e=>{let lane=codes.indexOf(e.code);if(lane>=0){held.delete(lane);game.querySelectorAll('.lane')[lane]?.classList.remove('held');if(started&&activeSustains.some(x=>x.lane===lane&&x.until>gameMs()+60)){activeSustains=activeSustains.filter(x=>x.lane!==lane);miss()}}},true);
$('#sdb-start').onclick=()=>{if(!player())return;judged.clear();activeSustains=[];nodes.forEach(n=>n.remove());nodes.clear();combo=score=0;updateHud();command('seekTo',[0,true]);command('setVolume',[100]);command('playVideo');started=true;requestAnimationFrame(loop)};$('#sdb-pause').onclick=()=>{started=!started;command(started?'playVideo':'pauseVideo');if(started)requestAnimationFrame(loop)};$('#sdb-offset').onchange=async e=>{offset=Number(e.target.value)*1000||0;await saveBassSettings()};$('#sdb-volume').oninput=e=>volume=+e.target.value;$('#sdb-volume').onchange=saveBassSettings;$('#sdb-back').onclick=()=>history.back();setInterval(()=>{if(player())iframe.contentWindow.postMessage(JSON.stringify({event:'listening',id:iframe.id,channel:'sdb'}),'*')},300);load();
})();