(()=>{
if(window.__sdgUpdater)return;window.__sdgUpdater=true;
const DB='sdg-updater',STORE='handles',HANDLE_KEY='extension-root';let directoryHandle=null;
const panel=document.createElement('section');panel.style.cssText='margin-top:18px;padding:14px;background:#202630;border:1px solid #3b4658;border-radius:11px';panel.innerHTML='<h2 style="font-size:18px;margin:0 0 10px">開發版更新</h2><label class="label">GitHub update.json 網址</label><input id="sdg-update-url" class="field" placeholder="https://raw.githubusercontent.com/.../update.json"><div style="display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:8px"><button id="sdg-pick-folder" style="padding:10px;background:#59677d">選擇插件資料夾</button><button id="sdg-check-update" style="padding:10px;background:#2878e8">檢查並套用更新</button></div><div id="sdg-update-folder" style="margin-top:9px;color:#9ca9bc;font-size:12px">尚未授權插件資料夾</div><pre id="sdg-update-log" style="max-height:150px;overflow:auto;margin:10px 0 0;padding:8px;background:#090d14;color:#8ee9ff;border-radius:6px;font:10px/1.45 Consolas;white-space:pre-wrap"></pre>';document.querySelector('aside')?.append(panel);
const $=s=>panel.querySelector(s),logBox=$('#sdg-update-log');function log(message){logBox.textContent+=`[${new Date().toLocaleTimeString('zh-TW',{hour12:false})}] ${message}\n`;logBox.scrollTop=logBox.scrollHeight}
function openDb(){return new Promise((resolve,reject)=>{let request=indexedDB.open(DB,1);request.onupgradeneeded=()=>request.result.createObjectStore(STORE);request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)})}
async function saveHandle(handle){let db=await openDb();await new Promise((resolve,reject)=>{let tx=db.transaction(STORE,'readwrite'),r=tx.objectStore(STORE).put(handle,HANDLE_KEY);r.onsuccess=resolve;r.onerror=()=>reject(r.error)});db.close()}
async function loadHandle(){let db=await openDb(),handle=await new Promise((resolve,reject)=>{let tx=db.transaction(STORE),r=tx.objectStore(STORE).get(HANDLE_KEY);r.onsuccess=()=>resolve(r.result||null);r.onerror=()=>reject(r.error)});db.close();return handle}
async function permission(handle,request=false){if(!handle)return false;let options={mode:'readwrite'},state=await handle.queryPermission(options);if(state==='granted')return true;return request&&(await handle.requestPermission(options))==='granted'}
function versions(a,b){let aa=String(a).split('.').map(Number),bb=String(b).split('.').map(Number);for(let i=0;i<Math.max(aa.length,bb.length);i++){let d=(aa[i]||0)-(bb[i]||0);if(d)return d}return 0}
function hex(buffer){return [...new Uint8Array(buffer)].map(x=>x.toString(16).padStart(2,'0')).join('')}
function u16(v,o){return v.getUint16(o,true)}function u32(v,o){return v.getUint32(o,true)}
async function unzip(buffer){let bytes=new Uint8Array(buffer),view=new DataView(buffer),eocd=-1;for(let i=bytes.length-22;i>=Math.max(0,bytes.length-65557);i--)if(u32(view,i)===0x06054b50){eocd=i;break}if(eocd<0)throw Error('ZIP 找不到中央目錄');let count=u16(view,eocd+10),offset=u32(view,eocd+16),decoder=new TextDecoder,entries=[];for(let i=0;i<count;i++){if(u32(view,offset)!==0x02014b50)throw Error('ZIP 中央目錄損壞');let method=u16(view,offset+10),size=u32(view,offset+24),nameLen=u16(view,offset+28),extraLen=u16(view,offset+30),commentLen=u16(view,offset+32),local=u32(view,offset+42),name=decoder.decode(bytes.slice(offset+46,offset+46+nameLen));offset+=46+nameLen+extraLen+commentLen;if(name.endsWith('/'))continue;if(name.startsWith('/')||name.includes('..')||name.includes('\\'))throw Error(`ZIP 包含不安全路徑：${name}`);if(![0,8].includes(method))throw Error(`不支援 ZIP 壓縮方法 ${method}`);if(u32(view,local)!==0x04034b50)throw Error('ZIP 本機標頭損壞');let ln=u16(view,local+26),le=u16(view,local+28),compressed=u32(view,local+18),start=local+30+ln+le,data=bytes.slice(start,start+compressed);if(method===8){let stream=new Blob([data]).stream().pipeThrough(new DecompressionStream('deflate-raw'));data=new Uint8Array(await new Response(stream).arrayBuffer())}if(data.length!==size)throw Error(`ZIP 解壓大小錯誤：${name}`);entries.push({name,data})}return entries}
function stripRoot(entries){let roots=new Set(entries.map(x=>x.name.split('/')[0]));if(roots.size===1&&entries.every(x=>x.name.includes('/'))){let root=[...roots][0]+'/';return entries.map(x=>({...x,name:x.name.slice(root.length)}))}return entries}
async function childDirectory(root,parts){let dir=root;for(let part of parts)dir=await dir.getDirectoryHandle(part,{create:true});return dir}
async function writeEntries(root,entries){let manifest=entries.find(x=>x.name==='manifest.json');if(!manifest)throw Error('ZIP 根目錄找不到 manifest.json');let parsed=JSON.parse(new TextDecoder().decode(manifest.data)),latest=window.__sdgPendingUpdate;if(parsed.version!==latest.version)throw Error(`ZIP Manifest 版本 ${parsed.version} 與 update.json ${latest.version} 不一致`);for(let entry of entries.filter(x=>x!==manifest)){let parts=entry.name.split('/'),file=parts.pop(),dir=await childDirectory(root,parts),handle=await dir.getFileHandle(file,{create:true}),writer=await handle.createWritable();await writer.write(entry.data);await writer.close()}let handle=await root.getFileHandle('manifest.json',{create:true}),writer=await handle.createWritable();await writer.write(manifest.data);await writer.close()}
async function validateRoot(handle){let file=await (await handle.getFileHandle('manifest.json')).getFile(),manifest=JSON.parse(await file.text());if(!manifest.name||!manifest.version)throw Error('選取的資料夾不是有效插件根目錄');return manifest}
$('#sdg-pick-folder').onclick=async()=>{try{if(!window.showDirectoryPicker)throw Error('目前 Chrome 不支援資料夾寫入 API');let handle=await showDirectoryPicker({mode:'readwrite'}),manifest=await validateRoot(handle);if(!await permission(handle,true))throw Error('未取得資料夾寫入權限');directoryHandle=handle;await saveHandle(handle);$('#sdg-update-folder').textContent=`已授權：${handle.name}（目前 ${manifest.version}）`;log(`插件資料夾已設定：${handle.name}`)}catch(error){log(`設定失敗：${error.message}`)}};
$('#sdg-check-update').onclick=async()=>{let button=$('#sdg-check-update');button.disabled=true;try{let updateUrl=$('#sdg-update-url').value.trim();if(!updateUrl)throw Error('請先輸入 update.json 網址');localStorage.setItem('sdgUpdateUrl',updateUrl);if(!directoryHandle)directoryHandle=await loadHandle();if(!directoryHandle||!await permission(directoryHandle,true))throw Error('請先選擇並授權插件資料夾');let current=await validateRoot(directoryHandle);log(`檢查更新：目前 ${current.version}`);let response=await fetch(updateUrl,{cache:'no-store'});if(!response.ok)throw Error(`update.json HTTP ${response.status}`);let update=await response.json();if(!update.version||!update.zipUrl||!update.sha256)throw Error('update.json 缺少 version、zipUrl 或 sha256');if(versions(update.version,current.version)<=0){log(`目前已是最新版 ${current.version}`);return}window.__sdgPendingUpdate=update;log(`發現新版 ${update.version}，下載 ZIP…`);let zipUrl=new URL(update.zipUrl,updateUrl).href,zipResponse=await fetch(zipUrl,{cache:'no-store'});if(!zipResponse.ok)throw Error(`ZIP HTTP ${zipResponse.status}`);let buffer=await zipResponse.arrayBuffer();if(buffer.byteLength>100*1024*1024)throw Error('ZIP 超過 100MB 安全上限');let digest=hex(await crypto.subtle.digest('SHA-256',buffer));if(digest.toLowerCase()!==String(update.sha256).toLowerCase())throw Error('SHA-256 驗證失敗，已停止覆蓋');log(`SHA-256 正確，解壓 ${Math.round(buffer.byteLength/1024)}KB…`);let entries=stripRoot(await unzip(buffer));log(`驗證完成，共 ${entries.length} 個檔案；開始覆蓋`);await writeEntries(directoryHandle,entries);log(`更新檔案已套用至 ${update.version}`);$('#status').textContent=`更新至 ${update.version} 已寫入。請到 chrome://extensions 對插件按「重新載入」`;}catch(error){log(`更新失敗：${error.message}`);$('#status').textContent='更新失敗：'+error.message}finally{button.disabled=false}};
$('#sdg-update-url').value=localStorage.getItem('sdgUpdateUrl')||'';loadHandle().then(async handle=>{if(handle){directoryHandle=handle;let granted=await permission(handle,false);$('#sdg-update-folder').textContent=granted?`已記住：${handle.name}`:`已記住 ${handle.name}，更新時會再次要求權限`}}).catch(error=>log(`讀取資料夾授權失敗：${error.message}`));log(`更新器就緒 v${chrome.runtime.getManifest().version}`);
})();
